source/PROJECT-INFO.txt
source/release-notes-2.0.14.rst
source/release-notes.rst

modified:   source/PROJECT-INFO.txt
new file:   source/release-notes-2.0.14.rst

proxysql-admin-tool-doc-2.0.14 Release notes: 2.0.14

---

source/installing-tarball.rst
source/release-notes-2.0.14.rst

modified:   source/installing-tarball.rst
modified:   source/release-notes-2.0.14.rst

psqladmin-266 update installation doc

---

source/installing-tarball.rst
source/proxysql-v2.rst

Modified source/installing-tarball

PSQLADM-275 UpdateProxySQL tarball installation

---

source/release-notes-2.0.15.rst
source/release-notes.rst

new file:   source/release-notes-2.0.15.rst

PSQLADM-270 Release Notes for proxysql-admin-tool-doc-2.0.15 (2.0.15)

---

source/_res/links.txt
source/_res/text/release-notes/description.txt

modified:   _res/links.txt
modified:   _res/text/release-notes/description.txt

PSQLADM-278 Fix Download links

---

source/_res/text/release-notes/description-v2.txt
source/proxysql-v2.rst
source/release-notes-2.0.12.rst
source/release-notes-2.0.13.rst
source/release-notes-2.0.14.rst
source/release-notes-2.0.15.rst
source/release-notes-2.0.3.rst
source/release-notes-2.0.4.rst
source/release-notes-2.0.5.rst
source/release-notes-2.0.6.rst
source/release-notes-2.0.7.rst

modified:   source/_res/text/release-notes/description.txt
modified:   source/release-notes-2.0.12.rst
modified:   source/release-notes-2.0.13.rst
modified:   source/release-notes-2.0.14.rst
modified:   source/release-notes-2.0.15.rst
modified:   source/release-notes-2.0.3.rst
modified:   source/release-notes-2.0.4.rst
modified:   source/release-notes-2.0.5.rst
modified:   source/release-notes-2.0.6.rst
modified:   source/release-notes-2.0.7.rst

psqladm-279 Update release notes

---

source/PROJECT-INFO.txt
source/proxysql-v2.rst

modified:   source/PROJECT-INFO.txt
modified:   source/proxysql-v2.rst

psqladm-281 Additions to admin file

---

source/release-notes-2.0.17.rst
source/release-notes.rst

new file:   source/release-notes-2.0.17.rst

PROXYSQLADM-296 Release Notes for proxysql-admin-tool-doc-2.0.17

---

source/release-notes-2.0.17.rst

modified:   source/release-notes-2.0.17.rst

PSQLADM-304 Update text

---

source/_res/links.txt
source/_res/text/release-notes/description-v2.txt
source/_res/text/release-notes/description.txt
source/_res/text/release-notes/upstream.txt
source/release-notes-2.0.17.rst

modified:   source/_res/links.txt
modified:   source/release-notes-2.0.17.rst
modified:   source/_res/text/release-notes/description-v2.txt
modified:   source/_res/text/release-notes/description.txt
modified:   source/_res/text/release-notes/upstream.txt

PSQLADM-307 Update text

---

source/PROJECT-INFO.txt
source/release-notes-2.0.18.rst
source/release-notes.rst

modified:   source/PROJECT-INFO.txt
new file:   source/release-notes-2.0.18.rst

PSQLADM-312 Release Notes for ProxySQL 2.0.18

---

Makefile

PSQLADM-308 Ability to build themed docs

---

source/_res/links.txt
source/installing-tarball.rst
source/proxysql-v2.rst
source/release-notes-2.1.1.rst
source/release-notes.rst

new file:   source/release-notes-2.1.1
modified:   source/release-notes

PSQLADM-297 Release notes for 2.1.1

---

source/release-notes-2.1.1.rst

PSQLADM-325 Fix date (2.1.1)

---

source/release-notes-2.2.0.rst
source/release-notes.rst

Modified release-notes
Added release-notes-2.2.0

PSQLADM-326 - Release notes for 2.2.0

---

source/PROJECT-INFO.txt
source/conf.py
source/index.rst
source/release-notes-2.3.2.rst
source/release-notes.rst

modified:   source/PROJECT-INFO.txt
new file:   source/release-notes-2.3.2.rst

PSQLADM-348 Release Notes for 2.3.2 (2.3.2)

---

source/configuring.md
source/install-proxysql2.md
source/proxysql-v1.md
source/proxysql-v2.md
source/uninstalling.md

modified:   configuring.md
modified:   install-proxysql2.md
modified:   proxysql-v1.md
modified:   proxysql-v2.md
modified:   uninstalling.md

PSQLADM-342 Replace all occurrences of apt-get with apt (MD)

---

requirements.txt

PSQLADM-374 Align docs on Render with Percona website (Fix) 

---

source/conf.py

PSQLADM-374 Align docs on Render with Percona website (fix edit button)

---

README.md

PSQLADM-377 Fix link in README

---

source/release-notes.rst

PSQLADM-378 Add dates to Release notes index (2.x)

---

mkdocs-base.yml

PSQLADM-404 Fix the Edit this page link

---

_resource/overrides/partials/header.html
docs/index.md
mkdocs-base.yml
mkdocs-percona.yml
mkdocs.yml
requirements.txt

modified:  docs/index.md
modified:  mkdocs-percona.yml
new file: _resource/overrides/partials/header.html

PSQLADM-405 Add a link to the Percona label to lead to the main site

---

_resource/overrides/main.html

modified: ../_resource/overrides/main.html

PSQLADM-416 Point Contact Us to PSQLADM

---

docs/psa-options.md

PSQLADM-414 Fix internal links in psa-options.md (2.0.x)

---

docs/psa-config.md
docs/psa-options.md

M  docs/psa-config.md
M  docs/psa-options.md

PSQLADM-410 Refresh docs from recent README changes for 2.4.2 (2.0.x)

---

docs/2.4.2.md
docs/release-notes.md
mkdocs-base.yml

A  docs/2.4.2.md
M  docs/release-notes.md

PSQLADM-406 Release notes and release note tasks for 2.4.2

---

docs/2.4.2.md
docs/psa-scheduler.md

modified: docs/2.4.2.md
modified:   docs/psa-scheduler.md

PSQLADM-417 Add info about a fixed bug to 2.4.2 release notes

---

docs/2.4.3.md
docs/release-notes.md
mkdocs-base.yml

PSQLADM-418 2.4.3 release notes and release note tasks

---

docs/2.4.3.md

PSQLADM-420 Typo in release notes (2.4.3)

---

README.md

PSQLADM-386 Update Readme

---

docs/psa-ref.md

PSQLADM-427 remove slashes from commands

---

contributing.md
docs/2.4.2.md
docs/2.4.3.md
docs/2.4.4.md
docs/build-percona-scheduler-admin.md
docs/configure-proxysql1.md
docs/index.md
docs/install-proxysql2-tarball.md
docs/install-v2.md
docs/percona-scheduler-admin-known-limitations.md
docs/percona-scheduler-admin-options-detail.md
docs/percona-scheduler-admin-statements-options.md
docs/percona-scheduler-admin.md
docs/release-notes-1.4.6.md
docs/release-notes-2.0.13.md
docs/release-notes-2.0.14.md
docs/release-notes-2.0.15.md
docs/release-notes-2.0.17.md
docs/release-notes-2.0.18.md
docs/release-notes-2.1.1.md
docs/release-notes-2.2.0.md
docs/release-notes-2.3.2-1.md
docs/where-to-download-proxysql.md

M  2.4.3.md
M  2.4.4.md
M  build-percona-scheduler-admin.md
M  configure-proxysql1.md
M  index.md
M  install-v2.md
M  percona-scheduler-admin-known-limitations.md
M  percona-scheduler-admin-options-detail.md
M  percona-scheduler-admin-statements-options.md
M  release-notes-2.0.13.md
M  release-notes-2.0.17.md
M  release-notes-2.2.0.md
M  release-notes-2.3.2-1.md
M  where-to-download-proxysql.md

PSQLADM-435 Fix documentation links

---

docs/2.4.4-1.2.md
docs/release-notes.md
mkdocs-base.yml

PSQLADM-434 Release notes and release note tasks for ProxySQL 2.4.4-1.2

---

docs/release-notes.md

modified: docs/release-notes.md

PSQLADM-438 Fix link to the release notes

---

mkdocs-base.yml

PSQLADM-446 Fix two hyphens

---

docs/percona-scheduler-admin-configuration.md
docs/percona-scheduler-admin-known-limitations.md
docs/percona-scheduler-admin-options-detail.md
docs/percona-scheduler-admin-statements-options.md

modified:   docs/percona-scheduler-admin-options-detail.md

PSQLADM-447 Review options for two dashes

---

mkdocs-base.yml
requirements.txt

PSQLADM-448 Fix the global search field

---

docs/percona-scheduler-admin.md

modified:   docs/percona-scheduler-admin.md

PSQLADM-453 Update prerequisites text

---

docs/percona-scheduler-admin-configuration.md

modified:   docs/percona-scheduler-admin-configuration.md

PSQLADM-459 Document pingTimeout option

---

docs/2.4.8.md
docs/index.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

new file:   docs/2.4.8.md
modified:   docs/index.md
new file:   variables.yml

PSQLADM-467 Release notes for Proxysql 2.4.8

---

docs/install-proxysql2-tarball.md

modified:   docs/install-proxysql2-tarball.md

Add all the available tar files with descriptions

---

docs/2.5.1.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

modified:   docs/2.4.8.md
new file:   docs/2.5.1.md

PSQLADM-469 Release notes and release note tasks 2.5.1 

---

_resource/overrides/main.html

modified:   _resource/overrides/main.html

PSQLADM-477 Updated Google Tag Manager in the doc template

---

docs/copyright-and-licensing-information.md
docs/trademark-policy.md
mkdocs-base.yml

new file:   docs/copyright-and-licensing-information.md
new file:   docs/trademark-policy.md

DOCS-72 Update Trademark Policy, Copyright and Licensing Information (ProxySQL)

---

docs/2.5.3.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

PSQLADM-486 Document release notes for ProxySQL 2.5.3

---

docs/2.5.4.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

PSQLADM-490 2.5.4 Release notes and release note tasks

---

_resource/overrides/main.html

modified:   _resource/overrides/main.html

PSQLADM-494 Add pixel from DOCS-87

---

docs/2.5.5.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

PSQLADM-497 2.5.5 Release notes and release note tasks

---

mkdocs-base.yml

DOCS-98 Migrate form materialx to material.extensions (ProxySQL)

---

mkdocs-base.yml

DOCS-44 Dynamic copyright date in the documentation footer

---

docs/2.5.5-1.2.md
docs/copyright-and-licensing-information.md
docs/psh-detailed-options.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

On branch psqladm-509
new file:   docs/2.5.5-1.md
modified:   docs/copyright-and-licensing-information.md
https://dashboard.render.com/static/srv-cna918779t8c73c5qdn0/deploys/dep-cna93qocmk4c73a38cng
https://two-5-5-1.onrender.com/2.5.5-1.html

PSQLADM-509 ProxySQL 2.5.5-1.2 Release notes and release note tasks

---

mkdocs-base.yml

Remove copyright info from  mkdocs-base.yml (8.0)

---

docs/2.6.2.md
docs/install-proxysql2-tarball.md
docs/release-notes-index-v1.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

On branch psqladm-512
new file:   docs/2.6.0.md

PSQLADM-512 2.6.2 release notes and release note tasks

---

docs/2.6.3.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

On branch psqladm-516
new file:   docs/2.6.3.md
[2.6.3 release notes](https://proxysql-2-6-3-release-notes.onrender.com/2.6.3.html)
[Render generator for 2.6.3 release notes](https://dashboard.render.com/static/srv-cp7ka6vsc6pc73abm0vg/deploys/dep-cp7ka77sc6pc73abm190)

PSQLADM-516 Release notes and release notes tasks for ProxySQL 2.6.3

---

_resource/overrides/partials/header.html

DOCS-125 Reword Return link to Percona <technology> documentation

---

docs/2.6.4.md
docs/2.6.5.md
docs/build-psh.md
docs/install-v2.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

site:
[ProxySQL 2.6.5 release notes](https://proxysql-2-6-5-release-notes.onrender.com/2.6.5.html)
Render build:
[https://dashboard.render.com/static/srv-crdg86l2ng1s73fuk86g/deploys/dep-crdg86t2ng1s73fuk8d0](https://dashboard.render.com/static/srv-crdg86l2ng1s73fuk86g/deploys/dep-crdg86t2ng1s73fuk8d0)

PSQLADM-522 Documentation and release notes for ProxySQL 2.6.5

---

docs/2.7.1.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

new file:   docs/2.7.1.md
Render site
[Percona ProxySQL admin tools - ProxySQL 2.7.1 and ProxySQL admin tools (2024-10-)](https://proxysql-admin-tool-doc-wltl.onrender.com/2.7.1.html) 
Render build site
[Cloud Application Hosting for Developers | Render](https://dashboard.render.com/static/srv-cs3u7odumphs739d9dig/deploys/dep-cs3ud4o8fa8c73dht11g)

psqladm-529 Documentation and Release Notes for ProxySQL 2.7.1

---

docs/2.7.1.md
docs/build-psh.md
docs/index.md
docs/install-proxysql2-tarball.md
docs/install-v2.md
docs/upgrade-proxysql2.md
docs/where-to-download-proxysql.md

modified:   docs/2.7.1.md
modified:   docs/build-psh.md
modified:   docs/index.md
modified:   docs/install-proxysql2-tarball.md
modified:   docs/install-v2.md
modified:   docs/upgrade-proxysql2.md
modified:   docs/where-to-download-proxysql.md

PSQLADM-533 ProxySQL disclaimer for 8.4

---

docs/2.7.1-1.md
docs/release-notes.md
mkdocs-base.yml
variables.yml

new file:   docs/2.7.1-1.md
[2.7.1-1 release notes](https://proxysql-2-7-1-1-release-notes.onrender.com/2.7.1-1.html)
[Render dashboard](https://dashboard.render.com/static/srv-csrljo8gph6c73b8lq70/deploys/dep-csrljoggph6c73b8lqcg)

PSQLADM-536 [DOC]- Documentation and release notes for ProxySQL 2.7.1-1

---

docs/2.7.1-1.md
docs/2.7.3.md
docs/release-notes.md
mkdocs-base.yml
snippets/rn-ar.md
snippets/rn-block-top.md
variables.yml

modified:   docs/2.7.1-1.md
new file:   docs/2.7.3.md
new file:   snippets/rn-ar.md
new file:   snippets/rn-block-top.md

PSQLADM-557 [DOCS] - Release notes for ProxySQL 2.7.3

---

docs/2.7.3.md
snippets/rn-block-top.md

modified:   docs/2.7.3.md
modified:   snippets/rn-block-top.md

PSQLADM-561 [DOCS] - update release notes

---

docs/2.5.5-1.2.md
docs/2.6.2.md
docs/2.6.3.md
docs/2.6.5.md
docs/2.7.1-1.md
docs/2.7.1.md
docs/2.7.3.md
docs/install-proxysql2-tarball.md
docs/install-v2.md
snippets/note-8.4.md
snippets/rn-block-top.md

modified:   docs/2.5.5-1.2.md
modified:   docs/2.6.2.md
modified:   docs/2.6.3.md
modified:   docs/2.6.5.md
modified:   docs/2.7.1-1.md
modified:   docs/2.7.1.md
modified:   docs/2.7.3.md
modified:   docs/install-proxysql2-tarball.md
modified:   docs/install-v2.md
new file:   snippets/note-8.4.md
modified:   snippets/rn-block-top.md
render - [update-proxysql](https://update-proxysql-docs.onrender.com)

PSQLADM-562 [DOCS] - Update release notes snippet
